config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :beers

  resources :breweries

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

  get 'beerlist', to: 'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'signup', to: 'users#new'

  get 'signin', to: 'sessions#new'

  get 'places', to: 'places#index'

  post 'places', to:'places#search'

  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :breweries do
    post 'toggle_activity', on: :member
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  	belongs_to :brewery
  	has_many :ratings, dependent: :destroy
  	has_many :raters, through: :ratings, source: :user
	
	include RatingAverage

  	validates :name, presence: true
	validates :style, presence: true	

  	def to_s
  		"#{name} (#{brewery.name})"
  	end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :set_breweries_and_styles_for_template, only: [:new, :edit, :create]
  before_action :ensure_that_signed_in, except: [:index, :show, :list, :nglist]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    order = params[:order] || 'name'

    @beers = case order
      when 'name' then @beers.sort_by{ |b| b.name }
      when 'brewery' then @beers.sort_by{ |b| b.brewery.name }
      when 'style' then @beers.sort_by{ |b| b.style }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @rating = Rating.new
    @rating.beer = @beer
  end

  # GET /beers/new
  def new
   @beer = Beer.new
 end

   def list
  end

    def nglist
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_breweries_and_styles_for_template
    @breweries = Brewery.all
    @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :style, :brewery_id)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.select :style, options_for_select(@styles) %>
  </div>
  <div class="field">
    <%= f.select :brewery_id, options_from_collection_for_select(@breweries, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beers</h1>

<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th> <%= link_to 'Name', beers_path(order:"name") %> </th>
        <th> <%= link_to 'Style', beers_path(order:"style") %> </th>
        <th> <%= link_to 'Brewery', beers_path(order:"brewery") %> </th>
      </tr>
    </thead>

    <tbody>
      <% @beers.each do |beer| %>
        <tr>
          <td><%= link_to beer.name, beer %></td>
          <td><%= link_to beer.style, beer.style %></td>
          <td><%= link_to beer.brewery.name, beer.brewery %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<button class="btn btn-primary"><%= link_to('New Beer', new_beer_path) if current_user %></button>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js"></script>
<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BeersController", function ($scope, $http) {
    $http.get('beers.json').success( function(data, status, headers, config) {
      $scope.beers = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order){
      $scope.order = order;
      console.log(order);
    }

    $scope.searchText = '';
  });
</script>

<h2>Beers</h2>

<div ng-app="myApp" ng-controller="BeersController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">name</a> </th>
    <th> <a ng-click="sort_by('style.name')">style</a> </th>
    <th> <a ng-click="sort_by('brewery.name')">brewery</a> </th>
    </thead>
    <tr ng-repeat="beer in beers| orderBy:order | filter:searchText">
      <td>{{beer.name}}</td>
      <td>{{beer.style}}</td>
      <td>{{beer.brewery.name}}</td>
    </tr>
  </table>

</div>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Style:</strong>
  <%= @beer.style %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery.name %>
</p>

<p>
<% if @beer.ratings.empty? %>
 beer has not yet been rated!
<% else %>
 Has <%= pluralize(@beer.ratings.count, 'rating') %>, average: <%= round(@beer.average_rating) %>
<% end %>
</p>

<% if current_user %>

  <h4>give a rating:</h4>

  <%= form_for(@rating) do |f| %>
    <%= f.hidden_field :beer_id %>
    score: <%= f.number_field :score %>
    <%= f.submit %>
  <% end %>

  <%= link_to 'Edit', edit_beer_path(@beer) %>

<% end %>
<%= link_to 'Back', beers_path %>